WEB_953505_EFIMCHIK/WEB_953505_EFIMCHIK/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB_953505_EFIMCHIK.Data;
using WEB_953505_EFIMCHIK.Models;
using WEB_953505_EFIMCHIK.Extensions;

namespace WEB_953505_EFIMCHIK.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private string cartKey = "cart";
        private Cart _cart;

        public CartController(ApplicationDbContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            //var _cart = HttpContext.Session.Get<Cart>(cartKey);
            return View(_cart.Items.Values);
        }
        [Authorize]
        public IActionResult Add(int id, string returnUrl)
        {
            //var _cart = HttpContext.Session.Get<Cart>(cartKey);
            var item = _context.Cars.Find(id);
            if (item != null)
            {
                _cart.AddToCart(item);
                HttpContext.Session.Set<Cart>(cartKey, _cart);
            }
            return Redirect(returnUrl);
        }
        public IActionResult Delete(int id)
        {
            _cart.RemoveFromCart(id);
            return RedirectToAction("Index");
        }
    }
}

WEB_953505_EFIMCHIK/WEB_953505_EFIMCHIK/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB_953505_EFIMCHIK.Data;
using WEB_953505_EFIMCHIK.Entities;
using WEB_953505_EFIMCHIK.Extensions;
using WEB_953505_EFIMCHIK.Models;

namespace WEB_953505_EFIMCHIK.Controllers
{
    public class ProductController : Controller
    {
        ApplicationDbContext _context;
        //List<Auto> _cars;
        //List<AutoGroup> _autoGroups;
        int _pageSize;
        private ILogger _logger;
        public ProductController(ApplicationDbContext context, ILogger<ProductController> logger)
        {
            _pageSize = 3;
            _context = context;
            _logger = logger;
            //SetupData();
        }

        [Route("Catalog")]
        [Route("Catalog/Page_{pageNo}")]
        public IActionResult Index(int? group, int pageNo = 1)
        {
            var autoFiltered = _context.Cars.Where(d => !group.HasValue ||
            d.AutoGroupId == group.Value);

            ViewData["Groups"] = _context.AutoGroups;
            ViewData["CurrentGroup"] = group ?? 0;

            //_logger.LogInformation($"info: group={group}, page={pageNo}");

            var model = ListViewModel<Auto>.GetModel(autoFiltered, pageNo, _pageSize);
            if (Request.IsAjaxRequest())
                return PartialView("_listpartial", model);
            else
                return View(model);
            //return View(ListViewModel<Auto>.GetModel(autoFiltered, pageNo, _pageSize));
        }
    }
}

WEB_953505_EFIMCHIK/WEB_953505_EFIMCHIK/Views/Product/Index.cshtml
@model ListViewModel<Auto>

@{
    ViewData["Title"] = "Каталог";

    var categories = ViewData["Groups"] as IEnumerable<AutoGroup>;
    int currentGroup = (int)ViewData["CurrentGroup"];

    var text = currentGroup != 0 ? categories.FirstOrDefault(g => g.AutoGroupId == currentGroup)?.GroupName : "Все";
}

<div class="row">
    <div class="col-2">
        <div class="dropdown mt-2">
            <a class="btn btn-secondary dropdown-toggle"
               asp-action="Index" asp-controller="Product"
               role="button"
               id="dropdownMenuLink"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                @text
            </a>
            <div class="dropdown-menu"
                 aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item"
                   asp-action="Index"
                   asp-controller="Product">
                    Все
                </a>
                @foreach (var item in categories)
                {
                    <a class="dropdown-item"
                       asp-action="Index"
                       asp-controller="Product"
                       asp-route-group="@item.AutoGroupId"
                       asp-route-pageNo="1">
                        @item.GroupName
                    </a>
                }
            </div>
        </div>
    </div>
    <div class="col-10">
        <div class="card-group" id="list">
            <partial name="_ListPartial" model="@Model" />
        </div>
        <pager page-current="@Model.CurrentPage"
               page-total="@Model.TotalPages"
               action="Index"
               controller="Product"
               group-id="@currentGroup">
        </pager>
    </div>
</div>

WEB_953505_EFIMCHIK/WEB_953505_EFIMCHIK/Views/Product/_ListItemPartial.cshtml
@model Auto

<div class='card m-2 p-1 text-center col-4'>
    <div class="embed-responsive embed-responsive-1by1">
        <img src="~/images/@Model.Image"
             alt="NoImage"
             class="card-img-top embed-responsive-item" />
    </div>
    <div class="card-body">
        <h5 class="card-title">
            @Model.AutoName
        </h5>
        <p class="card-text">
            @Model.Description
        </p>
        <div class="card-text badge badge-secondary">
            <h6>
                @Model.Price $
            </h6>
        </div>
        @{
            var request = ViewContext.HttpContext.Request;
            var returnUrl = request.Path + request.QueryString.ToUriComponent();
        }

        <p class="mt-2">
            <a asp-action="Add"
               asp-controller="Cart"
               asp-route-id="@Model.AutoId"
               asp-route-returnUrl="@returnUrl"
               class="btn btn-primary">
                <i class="fa fa-shopping-cart"></i>
                В корзину
            </a>
        </p>
    </div>
</div>

WEB_953505_EFIMCHIK/WEB_953505_EFIMCHIK/Views/Product/_ListPartial.cshtml
@model ListViewModel<Auto>
@foreach (var item in Model)
{
    <partial name="_ListItemPartial" model="@item" />
}