WEB_953505_EFIMCHIK/WEB_953505_EFIMCHIK/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB_953505_EFIMCHIK.Models;

namespace WEB_953505_EFIMCHIK.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private List<MenuItem> _menuItems = new List<MenuItem>
        {
            new MenuItem{ Controller="Home", Action="Index", Text="Lab 3"},
            new MenuItem{ Controller="Product", Action="Index", Text="Каталог"},
            new MenuItem{ IsPage=true, Area="Admin", Page="/Index", Text="Администрирование"}
        };

        public IViewComponentResult Invoke()
        {
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];
            foreach (var item in _menuItems)
            {
                var _matchController = controller?.Equals(item.Controller) ?? false;
                var _matchArea = area?.Equals(item.Area) ?? false;

                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }
    }
}

WEB_953505_EFIMCHIK/WEB_953505_EFIMCHIK/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB_953505_EFIMCHIK.Data;
using WEB_953505_EFIMCHIK.Models;
using WEB_953505_EFIMCHIK.Extensions;

namespace WEB_953505_EFIMCHIK.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private string cartKey = "cart";
        private Cart _cart;

        public CartController(ApplicationDbContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            //var _cart = HttpContext.Session.Get<Cart>(cartKey);
            return View(_cart.Items.Values);
        }
        [Authorize]
        public IActionResult Add(int id, string returnUrl)
        {
            //var _cart = HttpContext.Session.Get<Cart>(cartKey);
            var item = _context.Cars.Find(id);
            if (item != null)
            {
                _cart.AddToCart(item);
                HttpContext.Session.Set<Cart>(cartKey, _cart);
            }
            return Redirect(returnUrl);
        }
        public IActionResult Delete(int id)
        {
            _cart.RemoveFromCart(id);
            return RedirectToAction("Index");
        }
    }
}

WEB_953505_EFIMCHIK/WEB_953505_EFIMCHIK/Views/Shared/_Layout(copy).cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" asp-action="Index" asp-controller="HomeController">
                WebLabs_1
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-nav">
                <a class="nav-item nav-link active" asp-controller="Home" asp-action="Index"> Lab 2 </a>
                <a class="nav-item nav-link" asp-controller="Product" asp-action="Index"> Catalog </a>
                <a class="nav-item nav-link" asp-area="Admin" asp-page="/Index"> Admin </a>
            </div>

            <a asp-controller="Cart" asp-action="Index" class="navbar-text" ml-auto> 00,0 BYN <i class="fa fa-shopping-cart"></i> (0)</a>
            <div class="dropdown ml-4 nav-color">
                <div class="dropdown-toggle" id="dropdownMenuButton"
                     data-toggle="dropdown" aria-haspopup="true"
                     aria-expanded="false">
                    <img src="images/unnamed.jpg" width="30"
                         alt="User" class="rounded" />
                </div>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <div class="dropdown-item-text">
                        <img src="images/unnamed.jpg" width="50"
                             alt="User" class="rounded" />
                        user@gmail.com
                    </div>
                    <a class="dropdown-item" href="#"> My product </a>
                    <div class="dropdown-divider"></div>
                    <a class="drop-item" href="#"> Log out </a>
                </div>
            </div>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>

    <footer>
        <div class="navbar navbar-dark navbar-expand-md bg-dark">
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="http://www.facebook.com">
                    <i class="fab fa-facebook-f fa-2x"></i>
                </a>
                <a class="nav-item nav-link" href="http://www.vk.com">
                    <i class="fab fa-vk fa-2x"></i>
                </a>
                <a class="nav-item nav-link" href="https://web.telegram.org">
                    <i class="fab fa-telegram fa-2x"></i>
                </a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WEB_953505_EFIMCHIK/WEB_953505_EFIMCHIK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB_953505_EFIMCHIK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                WebLabs_3
            </a>
            <div class="navbar-nav">
                @await Component.InvokeAsync("Menu")
            </div>
            <partial name="_UserPartial" />
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>

    <footer>
        <div class="navbar navbar-dark navbar-expand-md bg-dark">
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="http://www.facebook.com">
                    <i class="fab fa-facebook-f fa-2x"></i>
                </a>
                <a class="nav-item nav-link" href="http://www.vk.com">
                    <i class="fab fa-vk fa-2x"></i>
                </a>
                <a class="nav-item nav-link" href="https://web.telegram.org">
                    <i class="fab fa-telegram fa-2x"></i>
                </a>
            </div>
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WEB_953505_EFIMCHIK/WEB_953505_EFIMCHIK/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using WEB_953505_EFIMCHIK.Entities;
@inject SignInManager<ApplicationUser> signInManager;

@if (signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ml-4 nav-color" style="position: relative; left: 1100px;">
        <div class="dropdown-toggle" id="dropdownMenuButton"
             data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            <img img-action="GetAvatar" img-controller="Image" width="30" alt="User" class="rounded bg-light" />
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item-text">
                <img img-action="GetAvatar" img-controller="Image" width="30" alt="User" class="rounded bg-light" />
                @User.Identity.Name
            </div>
            <a class="dropdown-item" href="#"> My product </a>
            <form asp-area="Identity" asp-page="/Account/Logout"
                  asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                <input type="submit" value="Log off" class="dropdown-item" />
            </form>
        </div>
    </div>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li>
            <a class="nav-item nav-link" asp-area="Identity"
               asp-page="/Account/Login">
                Войти
            </a>
        </li>
        <li>
            <a class="nav-item nav-link" asp-area="Identity"
               asp-page="/Account/Register">
                Зарегистрироваться
            </a>
        </li>
    </ul>
}